### ISSUE TITLE
site seems to be down

### ISSUE THREAD

**Issue by kigerpunk** [totallynuclearclub/totallynuclear.club#1]
http://isitup.org/totallynuclear.club

I was messing around with multiple ssh sessions, but that shouldn’t have placed too much strain on the system. I don’t know how AWS works, but can you just reboot?

**Comment by erikcore** [comment]
Just rebooted it. I'll need to investigate what happened there.

**Comment by erikcore** [comment]
I set up a status alarm to alert me if this happens again. At that point, I'll try to dig in and see what's going on. It looks like there was a spike in cpu usage, so somebody may have fired something up that started gobbling up resources.

**Comment by kigerpunk** [comment]
Is the alarm provided by Amazon, or is it a script of some sort? Also, is there any way to limit the amount of memory allowed to one process or user?

**Comment by erikcore** [comment]
The alarms can be set up through the amazon ec2 dashboard. Basically it just emails you to let you know if any basic tests have failed. That will at least alert me to when the site is down and I can start looking at the processes that are running.
