### ISSUE TITLE
Outbound email not delivered

### ISSUE THREAD

**Issue by Zaraka** [totallynuclearclub/totallynuclear.club#4]
Looks like I cant send email outside of totallynuclear.club domain

**Comment by kigerpunk** [comment]
That’s not an issue.

**Comment by Zaraka** [comment]
:/ I thought It would be great to send emails to people  from other tilde.clubs

**Comment by kigerpunk** [comment]
In that case, you may want to rephrase the issue; your current phrasing implies that something’s broken.

**Comment by erikcore** [comment]
@Zaraka There is talk of interconnected services between servers. Right now a few servers are linking up news servers and there is talk of potentially linking IRC. I'll keep everyone posted as things develop.
